### ISSUE TITLE
seed database fails

### ISSUE THREAD

**Issue by chirila** [YaleDHLab/voynich#54]
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-31-74bde42a4df7> in <module>()
     16   if not knn_map[i]: continue
     17   bns, sims = zip(*knn_map[i])
---> 18   knn_vals = [fig_to_meta[j] for j in bns]
     19   for jdx, j in enumerate(knn_vals):
     20     j['similarity'] = sims[jdx]

<ipython-input-31-74bde42a4df7> in <listcomp>(.0)
     16   if not knn_map[i]: continue
     17   bns, sims = zip(*knn_map[i])
---> 18   knn_vals = [fig_to_meta[j] for j in bns]
     19   for jdx, j in enumerate(knn_vals):
     20     j['similarity'] = sims[jdx]

KeyError: 1230

**Comment by duhaime** [comment]
I'll take a look at this one and the next in just a moment...
